{{ if eq .Values.filebeat "enable" }} 
{{- if (lookup "v1" "Configmap" "" "live") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: live
data:
  live.sh: |
      #
      #
      # Check if the die file is there and if then die
      FILE=/out/die
      if test -f "$FILE"; then
          echo "$FILE exists. i kill myself"
          sleep 5
          kill 1
      fi
      exit 0
{{ end }}
---
{{- if (lookup "v1" "Configmap" "" "filebeat") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
data:
  filebeat.yml: |
      #Read diffrent files types from /out folder
      filebeat.inputs:
      - type: log
        paths:
        - /out/*.json
        json.keys_under_root: true
        #json.add_error_key: true
      - type: log
        paths:
        - /out/*.xml
      - type: log
        paths:
        - /out/*.csv


      #Output to Elastic
      output.elasticsearch:
        hosts: '${ELASTICSEARCH:elasticsearch:9200}'
        index: samma-io.%{+yyyy.MM.dd}

        #username: '${ELASTICSEARCH_USERNAME:}'
        #password: '${ELASTICSEARCH_PASSWORD:}'


      #output.console:
      #  pretty: true


      #Adding the Samma-io Index and rollover 
      setup.ilm.enabled: auto
      setup.ilm.rollover_alias: "samma-io"
      setup.ilm.pattern: "{now/d}-000001"
      setup.template.name: "samma-io"
      setup.template.pattern: "samma-io*"
      logging.level: debug
{{ end }}
---
{{ end }}
{{ if eq .Values.cron.enable "false"  }}
apiVersion: batch/v1
kind: Job
metadata:
  name: nmap-port-scanner-{{ .Values.target | replace "." "-" }}
spec:
  template:
    spec:
      containers:
      - name: nmap-portscanner
        image: sammascanner/nmap:{{ .Values.image.tag}}
        command: ["python3","/code/nmap_portscanner.py","&","echo","'died_man_die'",">","/out/die"]
        env:
          - name: TARGET
            value: "{{ .Values.target }}"
          - name: SAMMA_IO_SCANNER
            value: "{{ .Values.samma.scanner }}"
          - name: SAMMA_IO_ID
            value: "{{ .Values.samma.id }}"
          - name: SAMMA_IO_TAGS
            value: "{{ .Values.samma.tags }}"
          - name: SAMMA_IO_JSON
            value: '{{ .Values.samma.json }}'
          - name: WRITE_TO_FILE
            value: "{{ .Values.samma.write_to_file }}"
          - name: PARSER
            value: "{{ .Values.samma.parser }}"
        volumeMounts:
          - mountPath: /out
            name: out-volume
      {{ if eq .Values.filebeat "enable" }} 
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        env:
          - name: ELASTICSEARCH
            value: "{{ .Values.elasticsearch }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - /live.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: filebeat
          mountPath: "/usr/share/filebeat/filebeat.yml"
          subPath: "filebeat.yml"
        - name: liveness
          mountPath: "/live.sh"
          subPath: "live.sh"
        - mountPath: /out
          name: out-volume
      {{ end }}
      volumes:
      {{ if eq .Values.filebeat "enable" }} 
      - name: filebeat
        configMap:
          name: filebeat
      - name: liveness
        configMap:
          name: live
          defaultMode: 0777
      {{ end }}
      - name: out-volume
        emptyDir: {}
      restartPolicy: Never
---

apiVersion: batch/v1
kind: Job
metadata:
  name: nmap-http-scanner-{{ .Values.target | replace "." "-" }}
spec:
  template:
    spec:
      containers:
      - name: nmap-httprecon
        image: sammascanner/nmap:{{ .Values.image.tag}}
        command: ["python3","/code/nmap_httprecon.py"]
        env:
          - name: TARGET
            value: "{{ .Values.target }}"
          - name: SAMMA_IO_SCANNER
            value: "{{ .Values.samma.scanner }}"
          - name: SAMMA_IO_ID
            value: "{{ .Values.samma.id }}"
          - name: SAMMA_IO_TAGS
            value: "{{ .Values.samma.tags }}"
          - name: SAMMA_IO_JSON
            value: '{{ .Values.samma.json }}'
          - name: WRITE_TO_FILE
            value: "{{ .Values.samma.write_to_file }}"
          - name: PARSER
            value: "{{ .Values.samma.parser }}"
        volumeMounts:
          - mountPath: /out
            name: out-volume
      {{ if eq .Values.filebeat "enable" }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        env:
          - name: ELASTICSEARCH
            value: "{{ .Values.elasticsearch }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - /live.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: filebeat
          mountPath: "/usr/share/filebeat/filebeat.yml"
          subPath: "filebeat.yml"
        - name: liveness
          mountPath: "/live.sh"
          subPath: "live.sh"
        - mountPath: /out
          name: out-volume
      {{ end }}
      volumes:
      {{ if eq .Values.filebeat "enable" }}
      - name: filebeat
        configMap:
          name: filebeat
      - name: liveness
        configMap:
          name: live
          defaultMode: 0777
      {{ end }}
      - name: out-volume
        emptyDir: {}
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nmap-tls-scanner-{{ .Values.target | replace "." "-" }}
spec:
  template:
    spec:
      containers:
      - name: nmap-tls
        image: sammascanner/nmap:{{ .Values.image.tag}}
        command: ["python3","/code/nmap_tlscipher.py"]
        env:
          - name: TARGET
            value: "{{ .Values.target }}"
          - name: SAMMA_IO_SCANNER
            value: "{{ .Values.samma.scanner }}"
          - name: SAMMA_IO_ID
            value: "{{ .Values.samma.id }}"
          - name: SAMMA_IO_TAGS
            value: "{{ .Values.samma.tags }}"
          - name: SAMMA_IO_JSON
            value: '{{ .Values.samma.json }}'
          - name: WRITE_TO_FILE
            value: "{{ .Values.samma.write_to_file }}"
          - name: PARSER
            value: "{{ .Values.samma.parser }}"
        volumeMounts:
          - mountPath: /out
            name: out-volume
      {{ if eq .Values.filebeat "enable" }}
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        env:
          - name: ELASTICSEARCH
            value: "{{ .Values.elasticsearch }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - /live.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: filebeat
          mountPath: "/usr/share/filebeat/filebeat.yml"
          subPath: "filebeat.yml"
        - name: liveness
          mountPath: "/live.sh"
          subPath: "live.sh"
        - mountPath: /out
          name: out-volume
        {{ end }}
      volumes:
     {{ if eq .Values.filebeat "enable" }}
      - name: filebeat
        configMap:
          name: filebeat
      - name: liveness
        configMap:
          name: live
          defaultMode: 0777
      {{ end }}
      - name: out-volume
        emptyDir: {}
      restartPolicy: Never
{{ end }}