{{ if .Values.target }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arachni-scanner-{{ .Values.target | replace "." "-" | replace "https://" "" | replace "http://" ""}}
spec:
  schedule: "{{ $.Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: arachni-portscanner
            image: sammascanner/arachni:{{ $.Values.image.tag }}
            env:
              - name: TARGET
                value: "{{ .Values.target }}"
          restartPolicy: Never
---




{{ else }}
{{- range .Values.targets }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arachni-scanner-{{ . | replace "." "-" | replace "https://" "" | replace "http://" ""}}
spec:
  schedule: "{{ $.Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: arachni-portscanner
            image: sammascanner/arachni:{{ $.Values.image.tag }}
            env:
              - name: TARGET
                value: "{{ . }}"
          restartPolicy: Never
---
{{ end }}
{{ end }}