kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-openvas-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress-openvas-pod
  template:
    metadata:
      labels:
        app: postgress-openvas-pod 
    spec:
      containers:
        - image: sammascanner/openvas-gvmd-postgres
          imagePullPolicy: Always
          name: postgress-openvas-pod
          env:
            - name: POSTGRES_USER
              value: gvmduser
            - name: POSTGRES_PASSWORD
              value: password
            - name:  GVMD_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: 'gvmd'
          ports:
            - containerPort: 5432
              name: sql
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: postgress
              mountPath: /var/lib/sql

      volumes:
        - name: postgress
          persistentVolumeClaim:
            claimName: postgress
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgress-openvas-pod
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: sql
  selector:
    app: postgress-openvas-pod