# Default values for samma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
proxyaccess: false 

samma_io: 
  id: 1234
  tags: ['scanner','prod']
  json: {"attacke":"true"}
  #Set what defualt scanner that are to be deployed
  scanner: nmap,nikto,tsunami
  #Add your console.samma.io key here 
  key: none


#
# Output are to be written to file and sent to elasticsearch
#

output:
  write_to_file: true
  elasticsearch: elasticsearch






#Deploy a elastic search for samma to store result in
elasticsearch:
    enabled: true
    volume: true
    disksize: 50G

grafana:
    enabled: true
    volume: true
    disksize: 50G

kibana:
    enabled: true
    