apiVersion: apiextensions.k8s.io/v1 
kind: CustomResourceDefinition 
metadata: 
  name: scanner.samma.io 
spec: 
  scope: Namespaced 
  group: samma-io
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                target:
                  type: string
                ip:
                  type: string
                scheduler:
                  type: string
                scanners:
                  type: array
                  items:
                    type: string
                samma_io_json:
                  type: string
                samma_io_id:
                  type: string
                samma_io_tags:
                  type: array
                  items:
                    type: string
                samma_io_profile:
                    type: string                    
                write_to_file:
                  type: string
                elasticsearch:
                  type: string

  names: 
    kind: Scanner
    plural: scanner
    singular: scanner 
    shortNames: 
      - sc