---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: samma-io
spec:
  replicas: 1
  selector:
    matchLabels:
      sammastack: kibana
  template:
    metadata:
      labels:
        sammastack: kibana
    spec:
      containers:
        - name: kibana
          image: "docker.elastic.co/kibana/kibana:7.15.0"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1G"
              cpu: "300m"
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: samma-io
spec:
  selector:
    sammastack: kibana
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601