# Default values for nmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: v0.2


#deploy as crontab
cron:
  enable: "false" # false for no crantab true for enabling cront scans
  schedule: "01 15 * * *"




#The target of the scanner. Evert target will get its own job
#
# nmap-tls-scanner-samma-io
target: "samma.io"

# Samma Values
samma:
  scanner: nmap
  id: 0000
  tags: "['scanner','base']"
  json: '{"extra":"value"}'
  write_to_file: "true" # any other string will disable it
  parser: nmap

#Send logs with filebeat to elasticsearch
filebeat: "enable" # any other string will disable it enbale to enable it
elastcisearch: http://elasticsearch:9200

