# Default values for nikto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: v0.2


#deploy as crontab
cron:
  enable: "false" # false for no crantab true for enabling cront scans
  schedule: "01 13 * * *"




#The target of the scanner. Evert target will get its own job
#
# nikto-scanner-samma-io
target: "samma.io"
tuning: 23
port: 443

# Samma Values
samma:
  scanner: nikto
  id: 0000
  tags: "['scanner','nikto']"
  json: '{"extra":"value"}'
  write_to_file: "true" # any other string will disable it
  parser: nikto

#Send logs with filebeat to elasticsearch
filebeat: "enable" # any other string will disable it enbale to enable it
elasticsearch: http://elasticsearch:9200

