#What version of the nmap scanenr do you want to run
image:
  tag: latest

#When do you want the scanners to run 
schedule: "30 * * * *"
#
# Ip ore dns name of you target.
# Every target will geta a job running

#Tuning
#This will set what type of scans nikto will run
#Defualt 23
tuning: 23


#Port
#This will set the port for the nikto scan
#Default 443
port: 443


#If you only use on target
target: ""


#If you want to run aginst multipel targets
# If you run any version unde target then targets will be skipped
targets:
  - www.elino.se
  - ollebo.com
  - samma.io
